from discord.ext import commands


class General(commands.Cog):
    """Minimal shared Discord event hooks."""

    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def manage_Kyohoon(self, message):
        # Ignore the bot's own events to prevent listeners from responding to
        # messages generated by other cogs.
        if message.author == self.bot.user:
            return


async def setup(bot):
    await bot.add_cog(General(bot))
